# Generated by Django 3.1.4 on 2020-12-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intra_id', models.CharField(max_length=30)),
                ('user_id', models.CharField(max_length=30)),
                ('photo', models.URLField(blank=True)),
                ('cur_wallet', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
