# Generated by Django 3.1.4 on 2020-12-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('achievement', models.CharField(max_length=30)),
                ('date', models.DateTimeField(verbose_name='checked date')),
            ],
        ),
        migrations.CreateModel(
            name='AchvList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('wallet_p', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='event date')),
                ('title', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('date', models.DateTimeField(verbose_name='checked date')),
                ('content', models.CharField(max_length=30)),
                ('get_wallet', models.SmallIntegerField(default=0)),
                ('spend_wallet', models.SmallIntegerField(default=0)),
                ('cur_wallet', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('price', models.SmallIntegerField(default=0)),
                ('photo', models.URLField(blank=True)),
            ],
        ),
    ]
