# Generated by Django 3.1.4 on 2020-12-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_achved_achvlist_notice_order_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='intra_id',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='achved',
            name='date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
